model_name: "densnet"

num_basis_fct: 114
emb_size: 10
num_interaction_blocks: 5
ao_vals: 10
num_grid_points: 900

num_train: 40
num_valid: 20
data_seed: 42
dataset: "data/md_h2.npz"
logdir: "./logging"

num_steps: 10000
ema_decay: 0.999

learning_rate: 0.001
warmup_steps: 3000
decay_rate: 0.01
decay_steps: 4000000

batch_size: 32
evaluation_interval: 100
save_interval: 1
restart: None
comment: "final"
target: ['densities']
